/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MotionBibliotecaRouteImport } from './routes/motion_.biblioteca'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionBibliotecaRoute = MotionBibliotecaRouteImport.update({
  id: '/motion_/biblioteca',
  path: '/motion/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motion': typeof MotionRoute
  '/motion/biblioteca': typeof MotionBibliotecaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motion': typeof MotionRoute
  '/motion/biblioteca': typeof MotionBibliotecaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motion': typeof MotionRoute
  '/motion_/biblioteca': typeof MotionBibliotecaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/motion' | '/motion/biblioteca'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/motion' | '/motion/biblioteca'
  id: '__root__' | '/' | '/motion' | '/motion_/biblioteca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotionRoute: typeof MotionRoute
  MotionBibliotecaRoute: typeof MotionBibliotecaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion_/biblioteca': {
      id: '/motion_/biblioteca'
      path: '/motion/biblioteca'
      fullPath: '/motion/biblioteca'
      preLoaderRoute: typeof MotionBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotionRoute: MotionRoute,
  MotionBibliotecaRoute: MotionBibliotecaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
